### ISSUE TITLE
Pathnames containing special characters (e.g. German umlauts) causes write.FCS to break measurement values

### ISSUE THREAD

**Issue by ccasar** [RGLab/flowCore#87]
I don't know if this is a file encoding issue or something else, but I took me time to figure out it was actually caused by the file pathnames:

```
library(flowCore)
# No Umlaut in pathname, everything is fine
orig_file <- "~/Documents/flowcore/no_umlaut/panel_a.fcs"
written_file <- "~/Documents/flowcore/out/written_panel_a.fcs"

first_read <- read.FCS(orig_file)
write.FCS(first_read,written_file)
second_read <- read.FCS(written_file)

summary(first_read)
APC-Cy7-A        
 Min.   :  -340.87  
 1st Qu.:    32.93  
 Median :   121.93  
 Mean   :   852.91  
 3rd Qu.:   242.97  
 Max.   :262143.00 
summary(second_read)
  APC-Cy7-A        
 Min.   :  -340.87  
 1st Qu.:    32.93  
 Median :   121.93  
 Mean   :   852.91  
 3rd Qu.:   242.97  
 Max.   :262143.00  

# Including Umlaut ü in pathname breaks the measurement values
orig_file_bad <- "~/Documents/flowcore/ü_umlaut/panel_a.fcs"
written_file_bad <- "~/Documents/flowcore/out/written_umlaut_panel_a.fcs"

first_read_bad <- read.FCS(orig_file_bad)
write.FCS(orig_read_bad,written_file_bad)
second_read_bad <- read.FCS(written_file_bad)

summary(first_read_bad)
  APC-Cy7-A        
 Min.   :  -340.87  
 1st Qu.:    32.93  
 Median :   121.93  
 Mean   :   852.91  
 3rd Qu.:   242.97  
 Max.   :262143.00  
summary(second_read_bad)
 APC-Cy7-A         
Min.   :-1.662e+37  
1st Qu.: 0.000e+00  
Median : 0.000e+00  
Mean   : 5.314e+34  
3rd Qu.: 0.000e+00  
Max.   : 2.031e+36 
```

**Comment by SamGG** [comment]
Hi,
Mike has changed the FCS default delimiter from "\" to "|". I think this change could avoid some problem in escaping characters. Could you rerun your code with flowcore v1.46.0 (R 3.5.0, Bioc 3.70)?
HTH

**Comment by ccasar** [comment]
Hi, I'll check this within the next few days and get back to you.

**Comment by ccasar** [comment]
Hi,
I've run the above code with

R version 3.5.1 (2018-07-02)
flowCore_1.46.1

The no Umlaut file still looks fine:
```
> summary(first_read)
         
          APC-Cy7-A
Min.           -340.8700
1st Qu.        32.9300
Median        121.9300
Mean           852.9055
3rd Qu.          242.9700
Max.     262143.0000

> summary(second_read)
              APC-Cy7-A
Min.         -340.8700
1st Qu.          32.9300
Median          121.9300
Mean           852.9055
3rd Qu.          242.9700
Max.       262143.0000

```
But the file with an Umlaut in it's name still creates different values after being written out and read back in (Also for some reason the summary format changed):

```
> summary(first_read_bad)
        APC-Cy7-A
Min.        -340.8700
1st Qu.     32.9300
Median          121.9300
Mean          852.9055
3rd Qu.          242.9700
Max.      262143.0000

> summary(second_read_bad)
$`APC-Cy7-A`
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-1.662e+37  0.000e+00  0.000e+00  5.314e+34  0.000e+00  2.031e+36 

```

Additionally I've tried setting `what = 'double'` when running write.FCS and again the only problem was with the written out umlaut file after reading it back in:

```
> summary(second_read_bad)

 APC-Cy7-A
Min.      0.000000e+00
1st Qu. 1.817929e-307
Median 1.825317e-307
Mean     7.976187e-306
3rd Qu.  1.857572e-307
Max.     4.687457e-305
```
Finally I tried to set the delimiter back to "", but immediately received an error:

```
write.FCS(first_read,written_file,delimiter="")
Error in gsub(double_delimiter, tempString, y, fixed = TRUE, useBytes = TRUE) : 
  zero-length pattern
```

Anything else I can do to help you solve this?

**Comment by gfinak** [comment]
Thanks for investigating further. Can you post the files here so we can reproduce this? We'll work on a fix.

**Comment by ccasar** [comment]
Due to size restrictions, I've only selected the first 500 cells from my example file. The bug still occurs but the values are different:
[flowcore.tar.gz](https://github.com/RGLab/flowCore/files/2302763/flowcore.tar.gz)

**Comment by gfinak** [comment]
Here's what I've found:

The files you provided have two $BEGINDATA and two $ENDDATA keywords (other keywords are duplicated as well) and they differ in their values AND are not consistent across the files (the file written with write.FCS differs from the other two).  
My guess, and I haven't investigated yet, is that `write.FCS` is adding its own keywords, and there may be a bug there.
I don't know if duplicated keywords are the problem or the calculation of their values is the problem.

@mikejiang, you recently dug into `write.FCS`, any insights?

``` r
library(flowCore)
setwd("~/Downloads/flowcore")
noum <- read.FCS("./no_umlaut/panel_a.fcs")
um <- read.FCS("./ü_umlaut/panel_a.fcs")
write.FCS(um,"./out/panel_a.fcs")
#> [1] "./out/panel_a.fcs"
bad <- read.FCS("./out/panel_a.fcs")

all.equal(noum[,"APC-Cy7-A"],
um[,"APC-Cy7-A"])
#> [1] "Attributes: < Component \"description\": Component \"FILENAME\": 1 string mismatch >"

all.equal(noum[,"APC-Cy7-A"],
          bad[,"APC-Cy7-A"])
#> [1] "Attributes: < Component \"description\": Component \"$BEGINDATA\": 1 string mismatch >"
#> [2] "Attributes: < Component \"description\": Component \"$ENDDATA\": 1 string mismatch >"  
#> [3] "Attributes: < Component \"description\": Component \"FILENAME\": 1 string mismatch >"
all.equal(um[,"APC-Cy7-A"],
          bad[,"APC-Cy7-A"])
#> [1] "Attributes: < Component \"description\": Component \"$BEGINDATA\": 1 string mismatch >"
#> [2] "Attributes: < Component \"description\": Component \"$ENDDATA\": 1 string mismatch >"  
#> [3] "Attributes: < Component \"description\": Component \"FILENAME\": 1 string mismatch >"


#Something is odd about the $BEGINDATA and $ENDDATA keywords

keyword(noum)[1:17]
#> $`$BEGINANALYSIS`
#> [1] "0"
#> 
#> $`$BEGINANALYSIS`
#> [1] "0"
#> 
#> $`$BEGINDATA`
#> [1] "5383"
#> 
#> $`$BEGINDATA`
#> [1] "4601"
#> 
#> $`$BEGINSTEXT`
#> [1] "0"
#> 
#> $`$BEGINSTEXT`
#> [1] "0"
#> 
#> $`$BTIM`
#> [1] "13:25:15"
#> 
#> $`$BYTEORD`
#> [1] "4,3,2,1"
#> 
#> $`$BYTEORD`
#> [1] "4,3,2,1"
#> 
#> $`$CYT`
#> [1] "LSRII"
#> 
#> $`$DATATYPE`
#> [1] "F"
#> 
#> $`$DATATYPE`
#> [1] "F"
#> 
#> $`$DATE`
#> [1] "13-JUL-2015"
#> 
#> $`$ENDANALYSIS`
#> [1] "0"
#> 
#> $`$ENDANALYSIS`
#> [1] "0"
#> 
#> $`$ENDDATA`
#> [1] "39382"
#> 
#> $`$ENDDATA`
#> [1] "27204600           "

#There are two $BEGINDATA and two #ENDDATA keywords, and they don't agree 
# with each other in the same file, or in the 
# "bad" and "noum" or "um" files.
# That said, the data read in are correct and consistent on this
# small example. I suspect on larger examples
# The *DATA keywords are causing truncated reading or something
# similar.
```

Created on 2018-08-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mikejiang** [comment]
duplicated keywords were caused by the bug that was fixed by 019318cc2ed77f1a9ca766e1246d0fc02f198cbd
But this issue is probably caused by the one umlaut symbol in the path `ü` that was inaccurately handled by `writeChar` when writing the FCS.
```r
> # No Umlaut in pathname, everything is fine
> orig_file1 <- "/loc/no-backup/mike/shared/flowcore/no_umlaut/panel_a.fcs"
> written_file1 <- "/tmp/a.fcs"
> 
> first_read1 <- read.FCS(orig_file1)
> write.FCS(first_read1,written_file1)
[1] "/tmp/a.fcs"
> second_read1 <- read.FCS(written_file1)
> range(second_read1, "data")[, 'APC-Cy7-A']
[1]  -226.06 14044.20
> 
> 
> orig_file2 <- "/loc/no-backup/mike/shared/flowcore/ü_umlaut/panel_a.fcs"
> first_read2 <- read.FCS(orig_file2)
> # keyword(first_read)[["FILENAME"]] <- "aa.fcs"
> written_file2 <- "/tmp/b.fcs"
> write.FCS(first_read2,written_file2)
[1] "/tmp/b.fcs"
> second_read2 <- read.FCS(written_file2)
> range(second_read2, "data")[, 'APC-Cy7-A']
[1] -1.004538e+33  2.022626e+36
> 
> # all.equal(keyword(second_read1), keyword(second_read2))
> 
> keyword(second_read1)[c("$BEGINDATA", "$ENDDATA", "FILENAME")]
$`$BEGINDATA`
[1] "5398"

$`$ENDDATA`
[1] "39397"

$FILENAME
[1] "/tmp/a.fcs"

> keyword(second_read2)[c("$BEGINDATA", "$ENDDATA", "FILENAME")]
$`$BEGINDATA`
[1] "5397"

$`$ENDDATA`
[1] "39396"

$FILENAME
[1] "/tmp/b.fcs"
```
As shown, the length of TEXT segment in FCS header is miscalculated (one byte off) for the file with `umlaut`. After I manually correct them in FCS, `read.FCS` was able to parse it correctly.

But I still need to get to the bottom of it so that the `umlaut` character can be handled properly.

**Comment by SamGG** [comment]
Hi,
No problem on my side (Win7, R3.5.0, flowCore 1.46.1)
```
> library(flowCore)

Attaching package: ‘flowCore’

The following object is masked from ‘package:EBImage’:

    normalize

> first_read <- read.FCS(orig_file)
> write.FCS(first_read,written_file)
[1] "C:/demo/flowcore/out/written_panel_a.fcs"
> second_read <- read.FCS(written_file)
> summary(first_read)
            FSC-A     FSC-H     FSC-W    SSC-A    SSC-H     SSC-W     FITC-A      PE-A
Min.     25110.81  25351.00  63904.24  15671.7  15340.0  62796.15   -39.6000   -64.900
1st Qu.  84322.79  62480.75  81789.48 108193.5  91509.5  74448.32   359.4250   466.950
Median  106682.45  78095.50  87830.15 141175.7 116835.5  77382.69   508.7500   618.200
Mean    114398.85  85889.59  88183.35 147768.1 123735.9  78620.94   883.6036  1092.991
3rd Qu. 131245.16  98129.00  92923.79 178664.8 144239.8  79760.48   680.6250   818.675
Max.    262143.00 256563.00 161547.88 262143.0 256910.0 143968.30 33181.5000 39953.102
        PerCP-Cy5-5-A   PE-Cy7-A  PE-Cy7-W     V405-A     V500-A live/dead-A
Min.         -140.800  -184.8000      0.00    -2.5500   -68.0000      -2.820
1st Qu.       681.725    69.0250  24498.95   168.0875   316.4125     417.830
Median        998.800   191.9500  44812.19   238.8500   494.2750     512.300
Mean         1857.121   386.3552  46908.38   572.3220  1185.1176    1266.537
3rd Qu.      1469.875   360.8000  65044.48   342.5500   708.9000     608.180
Max.        64400.602 22935.0000 262143.00 33304.6992 57352.9023   54587.680
        Alexa Fluor 647-A Alexa Fluor 700-A APC-Cy7-A
Min.            -145.0700          -73.8700  -226.060
1st Qu.           69.8650           83.2150    31.595
Median           120.1500          173.9950   121.485
Mean             268.0858          544.0071  1023.539
3rd Qu.          214.7125          322.8475   265.220
Max.            8345.5303        11383.0996 14044.200
> summary(second_read)
            FSC-A     FSC-H     FSC-W    SSC-A    SSC-H     SSC-W     FITC-A      PE-A
Min.     25110.81  25351.00  63904.24  15671.7  15340.0  62796.15   -39.6000   -64.900
1st Qu.  84322.79  62480.75  81789.48 108193.5  91509.5  74448.32   359.4250   466.950
Median  106682.45  78095.50  87830.15 141175.7 116835.5  77382.69   508.7500   618.200
Mean    114398.85  85889.59  88183.35 147768.1 123735.9  78620.94   883.6036  1092.991
3rd Qu. 131245.16  98129.00  92923.79 178664.8 144239.8  79760.48   680.6250   818.675
Max.    262143.00 256563.00 161547.88 262143.0 256910.0 143968.30 33181.5000 39953.102
        PerCP-Cy5-5-A   PE-Cy7-A  PE-Cy7-W     V405-A     V500-A live/dead-A
Min.         -140.800  -184.8000      0.00    -2.5500   -68.0000      -2.820
1st Qu.       681.725    69.0250  24498.95   168.0875   316.4125     417.830
Median        998.800   191.9500  44812.19   238.8500   494.2750     512.300
Mean         1857.121   386.3552  46908.38   572.3220  1185.1176    1266.537
3rd Qu.      1469.875   360.8000  65044.48   342.5500   708.9000     608.180
Max.        64400.602 22935.0000 262143.00 33304.6992 57352.9023   54587.680
        Alexa Fluor 647-A Alexa Fluor 700-A APC-Cy7-A
Min.            -145.0700          -73.8700  -226.060
1st Qu.           69.8650           83.2150    31.595
Median           120.1500          173.9950   121.485
Mean             268.0858          544.0071  1023.539
3rd Qu.          214.7125          322.8475   265.220
Max.            8345.5303        11383.0996 14044.200
> # Including Umlaut ü in pathname breaks the measurement values
> orig_file_bad <- "C:/demo/flowcore/ü_umlaut/panel_a.fcs"
> written_file_bad <- "C:/demo/flowcore/out/written_umlaut_panel_a.fcs"
> first_read_bad <- read.FCS(orig_file_bad)
> write.FCS(first_read_bad,written_file_bad)
[1] "C:/demo/flowcore/out/written_umlaut_panel_a.fcs"
> second_read_bad <- read.FCS(written_file_bad)
> summary(first_read_bad)
            FSC-A     FSC-H     FSC-W    SSC-A    SSC-H     SSC-W     FITC-A      PE-A
Min.     25110.81  25351.00  63904.24  15671.7  15340.0  62796.15   -39.6000   -64.900
1st Qu.  84322.79  62480.75  81789.48 108193.5  91509.5  74448.32   359.4250   466.950
Median  106682.45  78095.50  87830.15 141175.7 116835.5  77382.69   508.7500   618.200
Mean    114398.85  85889.59  88183.35 147768.1 123735.9  78620.94   883.6036  1092.991
3rd Qu. 131245.16  98129.00  92923.79 178664.8 144239.8  79760.48   680.6250   818.675
Max.    262143.00 256563.00 161547.88 262143.0 256910.0 143968.30 33181.5000 39953.102
        PerCP-Cy5-5-A   PE-Cy7-A  PE-Cy7-W     V405-A     V500-A live/dead-A
Min.         -140.800  -184.8000      0.00    -2.5500   -68.0000      -2.820
1st Qu.       681.725    69.0250  24498.95   168.0875   316.4125     417.830
Median        998.800   191.9500  44812.19   238.8500   494.2750     512.300
Mean         1857.121   386.3552  46908.38   572.3220  1185.1176    1266.537
3rd Qu.      1469.875   360.8000  65044.48   342.5500   708.9000     608.180
Max.        64400.602 22935.0000 262143.00 33304.6992 57352.9023   54587.680
        Alexa Fluor 647-A Alexa Fluor 700-A APC-Cy7-A
Min.            -145.0700          -73.8700  -226.060
1st Qu.           69.8650           83.2150    31.595
Median           120.1500          173.9950   121.485
Mean             268.0858          544.0071  1023.539
3rd Qu.          214.7125          322.8475   265.220
Max.            8345.5303        11383.0996 14044.200
> summary(second_read_bad)
            FSC-A     FSC-H     FSC-W    SSC-A    SSC-H     SSC-W     FITC-A      PE-A
Min.     25110.81  25351.00  63904.24  15671.7  15340.0  62796.15   -39.6000   -64.900
1st Qu.  84322.79  62480.75  81789.48 108193.5  91509.5  74448.32   359.4250   466.950
Median  106682.45  78095.50  87830.15 141175.7 116835.5  77382.69   508.7500   618.200
Mean    114398.85  85889.59  88183.35 147768.1 123735.9  78620.94   883.6036  1092.991
3rd Qu. 131245.16  98129.00  92923.79 178664.8 144239.8  79760.48   680.6250   818.675
Max.    262143.00 256563.00 161547.88 262143.0 256910.0 143968.30 33181.5000 39953.102
        PerCP-Cy5-5-A   PE-Cy7-A  PE-Cy7-W     V405-A     V500-A live/dead-A
Min.         -140.800  -184.8000      0.00    -2.5500   -68.0000      -2.820
1st Qu.       681.725    69.0250  24498.95   168.0875   316.4125     417.830
Median        998.800   191.9500  44812.19   238.8500   494.2750     512.300
Mean         1857.121   386.3552  46908.38   572.3220  1185.1176    1266.537
3rd Qu.      1469.875   360.8000  65044.48   342.5500   708.9000     608.180
Max.        64400.602 22935.0000 262143.00 33304.6992 57352.9023   54587.680
        Alexa Fluor 647-A Alexa Fluor 700-A APC-Cy7-A
Min.            -145.0700          -73.8700  -226.060
1st Qu.           69.8650           83.2150    31.595
Median           120.1500          173.9950   121.485
Mean             268.0858          544.0071  1023.539
3rd Qu.          214.7125          322.8475   265.220
Max.            8345.5303        11383.0996 14044.200
> packageVersion("flowCore")
[1] ‘1.46.1’
> 
```

In Mike's code, the second_read1 originated from the no_umlaut folder whereas the second_read2 occurs from the u_umlaut. Since the filename keyword written in the header includes one more character, data starts 1 octet later. So it's OK.
![2018-08-20_203937](https://user-images.githubusercontent.com/3333348/44361019-ec4bd600-a4bc-11e8-9994-fa9f13fa9154.png)

Duplicated keywords are in the original file, and is not corrected in my version.
![2018-08-20_210204](https://user-images.githubusercontent.com/3333348/44361033-f53ca780-a4bc-11e8-80e1-9350db9a576e.png)

HTH

**Comment by mikejiang** [comment]
For me, `writeChar` writes 9-character string `Ã¼_umlaut` instead of  8-byte `ü_umlaut`. However, I still don't know how to fix it.

**Comment by gfinak** [comment]
Could this be dependent on system locale?

**Comment by SamGG** [comment]
Probably. Mine:
```
> Sys.getlocale()
[1] "LC_COLLATE=English_United Kingdom.1252;LC_CTYPE=English_United Kingdom.1252;LC_MONETARY=English_United Kingdom.1252;LC_NUMERIC=C;LC_TIME=English_United Kingdom.1252"
```

**Comment by gfinak** [comment]
Sys.getlocale()
[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8"

```
library(flowCore)
f = file("~/Downloads/test.txt")
print("\303\274")
[1] "ü"
writeChar(con=f, "\303\274")
close(f)
readLines("~/Downloads/test.txt")
1: In readLines("~/Downloads/test.txt") :
  line 1 appears to contain an embedded nul
[1] "ü"
```
The output of `writeChar` is also 3 bytes, with the last byte being NUL.


Unfortunately I can't change my locale with `Sys.setlocale()`

**Comment by mikejiang** [comment]
```r
> testfile <- "/tmp/c.txt"
> var <- "ü"
> nchar(var)
[1] 1
> con <- file(testfile, open="wb")
> writeChar(var, con, eos=NULL)
> close(con)
> file.info(testfile)[["size"]]
[1] 2
```
Here is the root cause, the `write.FCS` uses `nchar` to compute the bytes to set FCS header, which counts the umlaut as single byte, but `writeChar` writes it as two-byte character.
The fix is to specify the `type` for `nchar`, i.e.
```r
> nchar(var, "bytes")
[1] 2
```
So that the header information will be consistent with the actual bytes written.

**Comment by SamGG** [comment]
Sounds OK on my side.
```
> nchar("ü", type = "bytes")
[1] 1
> nchar("ü", type = "char")
[1] 1
```

**Comment by mikejiang** [comment]
Because your locale encodes it as single-byte character. But we want to be robust enough to handle the system that behaves differently than yours.

**Comment by mikejiang** [comment]
Ok. @ccasar the latest commit should fix your problem.
@SamGG , feel free to test it out as well.
